language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Pur_Beurre_Nuttela.settings.travis"

branches:
  only:
          - staging

services:
  - postgresql

script:
  - ./Pur_Beurre_Nutella/manage.py test mes_aliments.tests.unittest
  - ./Pur_Beurre_Nutella/manage.py test mes_aliments.tests.functional_test
