language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Pur_Beurre_Nuttela.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test mes_aliments.tests.unittest
  - ./manage.py test mes_aliments.tests.functional_test
